### PR TITLE
fix #639 fix semantics of topicOfInterest

### LINKED ISSUE #639: [Bug] topicsOfInterest should pass a reference instead of a value
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/apache/rocketmq-clients/issues) and [GitHub Discussions](https://github.com/apache/rocketmq-clients/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Programming Language of the Client

C++

### Runtime Platform Environment

all

### RocketMQ Version of the Client/Server

all 

### Run or Compiler Version

_No response_

### Describe the Bug

void SimpleConsumerImpl::topicsOfInterest(std::vector<std::string> topics) {
  absl::MutexLock lk(&subscriptions_mtx_);
  for (const auto& entry : subscriptions_) {
    if (std::find(topics.begin(), topics.end(), entry.first) == topics.end()) {
      topics.push_back(entry.first);
    }
  }
}

Based on the topicsOfInterest function's intention, which is to modify the input parameter, it should pass a reference instead of a value.

### Steps to Reproduce

code error

### What Did You Expect to See?

Input parameters are modified correctly

### What Did You See Instead?

The input parameters have not been modified

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lizhanhui**
### Which Issue(s) This PR Fixes

fix #639 

### Brief Description

Fix semantics of topicOfInterest, which should be a reader

### CODE REVIEW

File: cpp/source/rocketmq/ProducerImpl.cpp [hunk 1]
```diff
@@ -575,9 +576,22 @@ void ProducerImpl::onOrphanedTransactionalMessage(MessageConstSharedPtr message)
   }
 }
 
-void ProducerImpl::topicsOfInterest(std::vector<std::string> topics) {
+void ProducerImpl::topicsOfInterest(std::vector<std::string> &topics) {
   absl::MutexLock lk(&topics_mtx_);
-  topics_.swap(topics);
+  for (auto& topic : topics_) {
```
Comment (aaron-ai) [inline cpp/source/rocketmq/ProducerImpl.cpp:581]: Does `ProducerImpl#topicOfInterest` simply retrieve a copy of the topics for sending messages?

**Review by aaron-ai — APPROVED** [review]
Looks good overall.
